"""empty message

Revision ID: c736b1232603
Revises: 
Create Date: 2020-10-02 11:55:37.194006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c736b1232603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BMWCarTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Production', sa.String(), nullable=True),
    sa.Column('Model', sa.String(), nullable=True),
    sa.Column('Type', sa.String(), nullable=True),
    sa.Column('Displacement', sa.String(), nullable=True),
    sa.Column('Engine_Type', sa.String(), nullable=True),
    sa.Column('Power', sa.String(), nullable=True),
    sa.Column('Body', sa.String(), nullable=True),
    sa.Column('Production_Number', sa.String(), nullable=True),
    sa.Column('Image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BMWCarTable')
    # ### end Alembic commands ###
